### ISSUE TITLE
[REQUEST] For the max inventory code

### ISSUE THREAD

**Issue by NathanDreamweaver** [DaZombieKiller/SrDebug#1]
Could you please make it so instead of only slimes and food, we can also get resources and maybe plorts? (It would be like: Slime, Slime, Resource, Plort, Food)

**Comment by DaZombieKiller** [comment]
I'll definitely look into this for future versions. It shouldn't be too hard to add (I hope).

**Comment by NathanDreamweaver** [comment]
Thank you very much for considering it! I find it really hard to find the resources i want. Or you could do something else, maybe split it into two codes. The first one is like the already existing one, the second is: Resource, Resource, Resource, Resource, Plort or Plort, Plort, Plort, Plort, Resource.

**Comment by DaZombieKiller** [comment]
Added in 85a41aa377340e8c99facf908957d465522e66d9
Will be present in the next release

**Comment by DaZombieKiller** [comment]
Available in [0.6.0-b](https://github.com/DaZombieKiller/SrDebug/releases/tag/0.6.0-b)

**Comment by NathanDreamweaver** [comment]
Thank you, very, very much!
